### ISSUE TITLE
Add Mockoon

### ISSUE THREAD

**Issue by 255kb** [jondot/awesome-devenv#51]
I suggest that you add [Mockoon](https://mockoon.com), which is an API mocking desktop app. (disclaimer: I am the author). 
I wanted to create a pull request but I don't see a category where it could fit. 
What about creating a "Misc" section? 

Thanks :)

**Comment by jondot** [comment]
looks nice. just submit a pull request

**Comment by 255kb** [comment]
Closing because pull request was merged
